### PR TITLE
update scala-js to 0.6.8

### PR DESCRIPTION
**Pull request by hmil**

### CODE REVIEW

**Comment by sjrd** [comment]
You know that the most recent version is 0.6.9, right?

**Comment by hmil** [comment]
Haha no. I was looking for the badge on [this page](http://www.scala-js.org/libraries/) and used the most recent from the dropdown. Didn't even check the homepage :-°

By the way the badge is indeed broken [Scala.js](https://www.scala-js.org)

**Comment by sjrd** [comment]
> By the way the badge is indeed broken

What do you mean?

**Comment by hmil** [comment]
[This commit](https://github.com/scala-js/scala-js-website/commit/02b76e9f540e49cc9195a30cdf7ffde143531240) updated the file `_data/library/versions.yml` and created the badge `assets/badges/scalajs-0.6.8.svgassets/badges/scalajs-0.6.8.svg` whereas [that one](https://github.com/scala-js/scala-js-website/commit/c8369425fde28f465d96749f3e24bf39e2afa72a) did not. Therefore, there is no badge for v0.6.9.

**Comment by sjrd** [comment]
This is intentional. As the badge builder page explains:

> If you don’t find your version of Scala.js, that’s probably because it is forward-compatible with its predecessor, in which case you should take the latest available version older than your version of Scala.js. For example, for Scala.js 0.6.7, use the 0.6.6+ badge.

This also applies for 0.6.9: the 0.6.8+ badge should be used.

**Comment by hmil** [comment]
Ok my bad.

**Pull request merged**
