### PR TITLE
To scala 2.13 and scalajs 1.0

### PR DESCRIPTION
**Pull request by mathieuleclaire**
Use openjdk rather than oraclejdk
https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/2

### CODE REVIEW

**Comment by hmil** [comment]
Thanks a lot for your help. I will try to figure out how to reenable in-browser testing.

**Comment by mathieuleclaire** [comment]
You're welcome ! Thanks for finishing the job ! There are 2 errors in the CI checks that I do not reproduce locally:
- scalastyle complains
- [error] org.scalajs.testing.common.RPCCore$ClosedException:org.scalajs.testing.adapter.JSEnvRPC$RunTerminatedException

On, my machine, both tests work fine. Is the exception raised related to the browser testing ?
We are very close :)

**Comment by hmil** [comment]
It's the stress test which is pushing the vms on travis to their limits. You have disabled the browser tests in this PR.

**Comment by mathieuleclaire** [comment]
It sounds good for a release :)

**Pull request merged**
