### PR TITLE
Adds Scala 2.12 support

### PR DESCRIPTION
**Pull request by fedefernandez**
This PR upgrades the travis file and `crossScalaVersions` property.

And everything seems working fine. Please review at your convenience.

Thanks!

### CODE REVIEW

**Comment by fedefernandez** [comment]
Closing in favor of #56 

Sorry

**Comment by hmil** [comment]
Hi @fedefernandez did you re-open accidentally?

**Comment by fedefernandez** [comment]
Hi, I noticed those missing changes in Travis file and SBT crossScalaVersions property. Please, feel free to close it if it's not necessary.

**Comment by hmil** [comment]
Gotcha. The 2.12 build is failing though, it looks like a JRE version related issue. Could it be that scala 2.12 requires at least java 8?

**Comment by sjrd** [comment]
Yes, 2.12 requires at least Java 8.

**Comment by fedefernandez** [comment]
Yes, Java 8 is needed

**Comment by hmil** [comment]
Then I guess this snippet in the travis config should fix the build. Could you try that?
```
jdk:
  - oraclejdk8
```

**Comment by fedefernandez** [comment]
:+1:

**Comment by hmil** [comment]
Thanks @fedefernandez

**Pull request merged**
